apiVersion: {{ template "deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      release: {{ .Release.Name | quote }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: {{ template "chart" . }}
        release: {{ .Release.Name | quote }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      containers:
      - name: {{ template "fullname" . }}
        image: {{ template "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: VAULT_ADDR
          value: {{ .Values.vaultAddr | quote }}
        - name: VAULT_UNSEAL_TOKENS
          value: {{ .Values.unsealTokens | quote }}
        - name: VAULT_SKIP_VERIFY
          value: {{ .Values.skipTlsVerify | quote }}
        - name: TIMEOUT
          value: {{ .Values.timeout | quote }}
        {{- range $key, $value := .Values.extraEnvVars }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

