# Global Docker image parameters
# Please, note that this will override the image parameters, including dependencies, configured to use the global value
# Current available global Docker image parameters: imageRegistry
#
# global:
#   imageRegistry: myRegistryName

# String to partially override fullname template (will maintain the release name)
#
# nameOverride:

# String to fully override fullname template
#
# fullnameOverride:

# ref: https://hub.docker.com/r/trankchung/vault-unsealer/tags
#
image:
  registry: docker.io
  repository: tranchung/vault-unsealer
  tag: latest
  # Specify a imagePullPolicy
  # Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  # ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  #
  pullPolicy: IfNotPresent

# Full URL with port to Vault
vaultAddr: http://localhost:8200

# Space-separated list of unseal tokens
unsealTokens: key1 key2 keyN

# Ignore TLS verify
skipTlsVerify: false

# Timeout in seconds to perform unseal
timeout: 300

# Extra environtment variables to append to deployment
# Run `vault read --help` for list of available variables
extraEnvVars: {}

# Pod Upgrade Strategy
# ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
#
strategy: {}

# Pod Security Context
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
#
securityContext: {}

# Configure resource requests and limits
# ref: http://kubernetes.io/docs/user-guide/compute-resources/
#
resources: {}

# Node selector for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
#
nodeSelector: {}

# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
#
affinity: {}

